//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Layer
    {
        public int LayerID { get; set; }
        public string LayerName { get; set; }
        public string LayerProjection { get; set; }
        public string LayerBounds { get; set; }
        public int Layer_site { get; set; }
    }
}
